### ISSUE TITLE
HTTP Timeout Exception in GUI 1.0.9 Windows

### ISSUE THREAD

**Issue by PaddyD95** [mynttt/UpdateTool#130]
Had been running update tool for a year or so without issue. Stopped working a few months ago as it required me to specify SQLite location. Have now added that variable and updated from 1.08 to 1.09 (and not changed any other variable) but am now getting the following error:

[ERROR] - 2024-12-26 20:36:31 @ Main.lambda$main$1: Uncaught HttpConnectTimeoutException exception encountered...
[ERROR] - 2024-12-26 20:36:31 @ Main.lambda$main$1: Please contact the maintainer of the application with the stacktrace below if you think this is unwanted behavior.
[ERROR] - 2024-12-26 20:36:31 @ Main.lambda$main$1: ========================================
[ERROR] - 2024-12-26 20:36:31 @ Main.lambda$main$1: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:565)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at updatetool.common.externalapis.AbstractApi.send(AbstractApi.java:56)
	at updatetool.common.externalapis.TmdbApiV3.tmdbId2imdbId(TmdbApiV3.java:109)
	at updatetool.common.externalapis.TmdbApiV3.<init>(TmdbApiV3.java:37)
	at updatetool.imdb.ImdbDockerImplementation.bootstrap(ImdbDockerImplementation.java:118)
	at updatetool.Main.main(Main.java:86)
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:580)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:527)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:447)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:287)
	at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:250)
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:260)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:102)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1268)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:897)
Caused by: java.net.ConnectException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:581)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:527)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:447)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:287)
	at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:250)
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:260)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:102)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1268)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:897)
[ERROR] - 2024-12-26 20:36:31 @ Main.lambda$main$1: ========================================
[ERROR] - 2024-12-26 20:36:31 @ Main.lambda$main$1: The application will terminate now. (Version: 1.9.2)

**Comment by marcherschel** [comment]
Are you still getting that error? A timeout on the TMDB v3 API would either mean them having outages the moment you tried the tool or connection issues on your side.

If you still have them we can try to pin point it further.

**Comment by PaddyD95** [comment]
It's working now, thank you! Think I must have just been very unlucky with my timing, as I tried it 2 or 3 times weeks apart and kept getting the same thing. Thank you very much for your help.
