### ISSUE TITLE
Crash while using unraid docker - SAXParseException exception encountered

### ISSUE THREAD

**Issue by endiz** [mynttt/UpdateTool#41]
First time running this tool, it seems to run for awhile but then crashes before it can finish its xml updates.

```
*** VERSION 1.4.4 IS UP TO DATE! ***

MAX JVM HEAP: -Xmx256m
**** Invoking tool! Logs in /config ****
[INFO ] - 2020-10-15 18:41:21 @ Main.loadImplementation: Loaded implementation << imdb-docker << updatetool.imdb.ImdbDockerImplementation
[INFO ] - 2020-10-15 18:41:21 @ Main.main: Running version: 1.4.4

[INFO ] - 2020-10-15 18:41:21 @ Main.main: Args: {imdb-docker={schedule=24}}
[INFO ] - 2020-10-15 18:41:21 @ Main.main: << INIT: imdb-docker @ {schedule=24} >>
[INFO ] - 2020-10-15 18:41:21 @ ImdbDockerImplementation.bootstrap: No TMDB API key detected. Will not process TMDB backed Movie and TV Series libraries and TMDB orphans.
[INFO ] - 2020-10-15 18:41:21 @ ImdbDockerImplementation.bootstrap: No TVDB API authorization string detected. Will process TVDB backed TV Series libraries.
[INFO ] - 2020-10-15 18:41:21 @ ImdbDockerImplementation.bootstrap: Starting IMDB Watchdog
[INFO ] - 2020-10-15 18:41:21 @ ImdbDockerImplementation.bootstrap: Plex data dir: /plexdata
[INFO ] - 2020-10-15 18:41:21 @ ImdbDockerImplementation.bootstrap: Capabilities: [VERBOSE_XML_ERROR_LOG]
[INFO ] - 2020-10-15 18:41:21 @ Main.main: << INIT SUCCESS >>
[INFO ] - 2020-10-15 18:41:21 @ Scheduler.go: Scheduler is loading tasks... Blocking until completely set-up and ready to go.
[INFO ] - 2020-10-15 18:41:21 @ Scheduler.go: Scheduling tasks...
[INFO ] - 2020-10-15 18:41:21 @ Scheduler.lambda$go$0: Scheduled imdb-docker task to run @ every 24 hour(s).
[INFO ] - 2020-10-15 18:41:21 @ Scheduler.lambda$go$1: Queued task imdb-docker for immediate execution.
[INFO ] - 2020-10-15 18:41:21 @ Scheduler.go: Running supplied tasks immediately NOW!
[INFO ] - 2020-10-15 18:41:21 @ TaskWrapper.run: ================================================
[INFO ] - 2020-10-15 18:41:21 @ TaskWrapper.run: Starting task: imdb-docker | Execution count: 0
[INFO ] - 2020-10-15 18:41:21 @ TaskWrapper.run: ================================================
[INFO ] - 2020-10-15 18:41:22 @ ImdbDockerImplementation$ImdbBatchJob.run: Library IDs on ignore list: []
[INFO ] - 2020-10-15 18:41:22 @ ImdbRatingDatasetFactory.readData: Reading data...
[INFO ] - 2020-10-15 18:41:23 @ ImdbRatingDatasetFactory.readData: 1082987 lines read.
[WARN ] - 2020-10-15 18:41:23 @ NewPlexMovieAgentToImdbResolvement.<init>: No TMDB fallback set. Will not resolve new plex movie agent items if they only have a TMDB id associated.
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Movies has 1492 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Documentary Movies has 234 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Anime Movies has 26 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Stand-up has 263 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] UHD Movies has 52 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Processing [MOVIE] Movies with UUID f4eb9c28-6e74-486e-a4fc-e3600725f027 at stage: CREATED
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Resolving IMDB identifiers for items. Only warnings and errors will show up...
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Items that show up here will not be processed by further stages of the pipeline.
[WARN ] - 2020-10-15 18:41:23 @ DefaultResolvement.resolve: Item: 'After Life (1998)' has no matching IMDB resolver and will be ignored. (guid=com.plexapp.agents.none://376845842fa88de4aff45f8e2784aaf634dbe4e8?lang=xn)
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Filtered 1 invalid item(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: 1490 item(s) need no update.
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: Transforming 0 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: Transformed entries for 0 items(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateDatabase: Nothing to update. Skipping...
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateXML: Updating XML fallback files for 0 item(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateXML: Completed updating of XML fallback files.
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned PASS : Job finished correctly
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Job finished successfully for [MOVIE] Movies with UUID f4eb9c28-6e74-486e-a4fc-e3600725f027
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Processing [MOVIE] Documentary Movies with UUID b3bfe476-7961-4527-96d9-b97c739f3ffd at stage: CREATED
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Resolving IMDB identifiers for items. Only warnings and errors will show up...
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Items that show up here will not be processed by further stages of the pipeline.
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Filtered 0 invalid item(s).
[WARN ] - 2020-10-15 18:41:23 @ ImdbTransformer.needsUpdate: Ignoring: 'The Great Hack' with IMDB ID: tt9358204 supplies no valid rating := 'null'
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: 234 item(s) need no update.
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: Transforming 0 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: Transformed entries for 0 items(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateDatabase: Nothing to update. Skipping...
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateXML: Updating XML fallback files for 0 item(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateXML: Completed updating of XML fallback files.
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned PASS : Job finished correctly
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Job finished successfully for [MOVIE] Documentary Movies with UUID b3bfe476-7961-4527-96d9-b97c739f3ffd
[INFO ] - 2020-10-15 18:41:23 @ ImdbDockerImplementation$ImdbBatchJob.run: Processing [MOVIE] Anime Movies with UUID 8cee3e53-9260-4b72-910d-b0c7b281ebb8 at stage: CREATED
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Resolving IMDB identifiers for items. Only warnings and errors will show up...
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Items that show up here will not be processed by further stages of the pipeline.
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.analyseDatabase: Filtered 0 invalid item(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: 8 item(s) need no update.
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: Transforming 18 item(s)
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 7.9 -> 8.0 for Perfect Blue
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 7.8 -> 8.0 for Ghost in the Shell: Stand Alone Complex - Solid State Society
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Ghost in the Shell: Stand Alone Complex - Solid State Society
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 9.7 -> 8.5 for Grave of the Fireflies
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Grave of the Fireflies
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Grave of the Fireflies
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 7.9 -> 8.3 for Ghost in the Shell: Stand Alone Complex - The Laughing Man
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Ghost in the Shell: Stand Alone Complex - The Laughing Man
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 8.1 -> 8.4 for Ghost in the Shell: Stand Alone Complex - Individual Eleven
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Ghost in the Shell: Stand Alone Complex - Individual Eleven
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 10.0 -> 7.1 for Penguin Highway
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Penguin Highway
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Penguin Highway
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 8.1 -> 7.3 for Dragon Ball Z: Resurrection 'F'
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Dragon Ball Z: Resurrection 'F'
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Dragon Ball Z: Resurrection 'F'
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 7.6 -> 6.4 for Superman: Man of Tomorrow
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Superman: Man of Tomorrow
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 6.4 -> 7.5 for Ghost in the Shell 2: Innocence
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Ghost in the Shell 2: Innocence
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Ghost in the Shell 2: Innocence
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 7.7 -> 8.0 for Batman: The Dark Knight Returns
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Batman: The Dark Knight Returns
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 8.1 -> 8.0 for Castle in the Sky
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 8.7 -> 8.0 for Akira
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Akira
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Akira
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 9.7 -> 8.6 for Spirited Away
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Spirited Away
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Spirited Away
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 8.8 -> 7.7 for The Girl Who Leapt Through Time
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: The Girl Who Leapt Through Time
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: The Girl Who Leapt Through Time
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 9.6 -> 8.0 for Ghost in the Shell
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Ghost in the Shell
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Ghost in the Shell
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 9.4 -> 8.2 for My Neighbor Totoro
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: My Neighbor Totoro
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: My Neighbor Totoro
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 3.9 -> 6.4 for Batman: The Killing Joke
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Batman: The Killing Joke
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: Adjust rating: 8.3 -> 7.9 for Dragon Ball Super: Broly
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Remove) Stripping useless badge data (RT, TMDB) for: Dragon Ball Super: Broly
[INFO ] - 2020-10-15 18:41:23 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Dragon Ball Super: Broly
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.transformMetadata: Transformed entries for 18 items(s).
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateDatabase: Updating 18 via batch request...
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateDatabase: Batch request finished successfully. Database is now up to date!
[INFO ] - 2020-10-15 18:41:23 @ ImdbPipeline.updateXML: Updating XML fallback files for 18 item(s).
[Fatal Error] :1:1: Premature end of file.

[INFO ] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned ERROR : Premature end of file.

[ERROR] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: SAXParseException exception encountered...

[ERROR] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: Please contact the maintainer of the application with the stacktrace below if you think this is unwanted behavior.

[ERROR] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================

[ERROR] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: org.xml.sax.SAXParseException: Premature end of file.

at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
at java.xml/javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
at updatetool.imdb.ImdbXmlWorker.transformXML(ImdbXmlWorker.java:58)
at updatetool.imdb.ImdbXmlWorker.call(ImdbXmlWorker.java:45)
at updatetool.imdb.ImdbXmlWorker.call(ImdbXmlWorker.java:21)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
[ERROR] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================

[ERROR] - 2020-10-15 18:41:24 @ ImdbDockerImplementation$ImdbBatchJob.run: The application will terminate now.
```

**Comment by endiz** [comment]
Strange, i ran it this time WITH a TMDB api key (not sure if its a direct correlation) and it worked with no errors:

```
[INFO ] - 2020-10-15 21:13:07 @ ImdbTransformer.updateMetadata: (Set) Set IMDB Badge for: Pokémon Detective Pikachu
[INFO ] - 2020-10-15 21:13:07 @ ImdbPipeline.transformMetadata: Transformed entries for 52 items(s).
[INFO ] - 2020-10-15 21:13:07 @ ImdbPipeline.updateDatabase: Updating 52 via batch request...
[INFO ] - 2020-10-15 21:13:08 @ ImdbPipeline.updateDatabase: Batch request finished successfully. Database is now up to date!
[INFO ] - 2020-10-15 21:13:08 @ ImdbPipeline.updateXML: Updating XML fallback files for 52 item(s).
[INFO ] - 2020-10-15 21:13:08 @ ImdbPipeline.updateXML: Completed updating of XML fallback files.
[INFO ] - 2020-10-15 21:13:08 @ ImdbDockerImplementation$ImdbBatchJob.run: Job returned PASS : Job finished correctly
[INFO ] - 2020-10-15 21:13:08 @ ImdbDockerImplementation$ImdbBatchJob.run: Job finished successfully for [MOVIE] UHD Movies with UUID 2b54589d-61c7-437b-9be8-bfe9143f277a
[INFO ] - 2020-10-15 21:13:08 @ ImdbDockerImplementation$ImdbBatchJob.run: Completed batch successfully.
[INFO ] - 2020-10-15 21:13:08 @ TaskWrapper.run: ================================================
[INFO ] - 2020-10-15 21:13:08 @ TaskWrapper.run: Suggesting JVM to run the GC as soon as possible (Request might be ignored!)
[INFO ] - 2020-10-15 21:13:08 @ TaskWrapper.run: Completed imdb-docker in 4.055915s. - Invoking next task or going to sleep. It is safe to suspend execution if no other task is being invoked immediately.
```

**Comment by mynttt** [comment]
Thanks for letting me know! Looks like it ran into a malformed XML file. I will release a patch the next days that causes an ignore instead of a crash.
