### ISSUE TITLE
path to '/plexdata/Plug-in Support/Databases/com.plexapp.plugins.library.db': '/plexdata/Plug-in Support' does not exist

### ISSUE THREAD

**Issue by Skedooesh** [mynttt/UpdateTool#7]
Hey, I created a fresh Docker image from the commands listed in the Readme and got the following error when I checked the logs. 
Using the latest image released 4 hours ago.

```
**** Invoking tool! Logs in /config ****
[INFO ] - 2020-01-02 21:31:03 @ Main.main: Running version: 1.2.3
[INFO ] - 2020-01-02 21:31:03 @ Main.testApiImdb: Testing OMDB API key: XXXXXXX
[INFO ] - 2020-01-02 21:31:04 @ Main.genericApiTest: Test passed. API Key is valid.
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: No TMDB API key detected. Will not attempt to do an TMDB <=> IMDB ID conversion to update TMDB matched items (unless already matched previously).
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: Starting IMDB Watchdog
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: Plex data dir: /plexdata
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: Invoke every 24 hour(s)
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: Purge cache every 14 day(s)
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: Running first task...
[INFO ] - 2020-01-02 21:31:04 @ ImdbDockerImplementation.invoke: Scheduling next tasks to run @ every 24 hour(s)
[ERROR] - 2020-01-02 21:31:05 @ ImdbDockerImplementation$ImdbBatchJob.run: SQLException exception encountered...
[ERROR] - 2020-01-02 21:31:05 @ ImdbDockerImplementation$ImdbBatchJob.run: Please contact the maintainer of the application with the stacktrace below if you think this is unwanted behavior.
[ERROR] - 2020-01-02 21:31:05 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2020-01-02 21:31:05 @ ImdbDockerImplementation$ImdbBatchJob.run: java.sql.SQLException: path to '/plexdata/Plug-in Support/Databases/com.plexapp.plugins.library.db': '/plexdata/Plug-in Support' does not exist
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at updatetool.common.SqliteDatabaseProvider.<init>(SqliteDatabaseProvider.java:14)
        at updatetool.imdb.ImdbDockerImplementation$ImdbBatchJob.run(ImdbDockerImplementation.java:123)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] - 2020-01-02 21:31:05 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2020-01-02 21:31:05 @ ImdbDockerImplementation$ImdbBatchJob.run: The application will terminate now.
```

**Comment by mynttt** [comment]
It appears that you mapped an invalid path to /plex data. The mapped path should be the Plex data root, usually a folder named 'Plex Media Server'. It contains folders like Plug-in Support.

**Comment by Skedooesh** [comment]
Oh, I see. Thanks for the quick reply! I just copy pasted the plexmediaserver folder I used in CLI mode, I should have read the readme better for Docker mode.

Works great now, cheers!
