### ISSUE TITLE
Crash under truenas jail

### ISSUE THREAD

**Issue by tostlund** [mynttt/UpdateTool#75]
[INFO ] - 2021-11-14 13:16:27 @ Main.loadImplementation: Loaded implementation << imdb-docker << updatetool.imdb.ImdbDockerImplementation
[INFO ] - 2021-11-14 13:16:27 @ Main.main: Running version: 1.6.3
[INFO ] - 2021-11-14 13:16:27 @ Main.main: Args: {imdb-docker={schedule=1}}
[INFO ] - 2021-11-14 13:16:27 @ Main.main: << INIT: imdb-docker @ {schedule=1} >>
[INFO ] - 2021-11-14 13:16:27 @ ImdbDockerImplementation.bootstrap: No TMDB API key detected. Will not process TMDB backed Movie and TV Series libraries and TMDB orphans.
[INFO ] - 2021-11-14 13:16:27 @ ImdbDockerImplementation.bootstrap: No TVDB API authorization string detected. Will not process TVDB backed Movie and TV Series libraries.
[INFO ] - 2021-11-14 13:16:27 @ ImdbDockerImplementation.bootstrap: Starting IMDB Watchdog
[INFO ] - 2021-11-14 13:16:27 @ ImdbDockerImplementation.bootstrap: Plex data dir: /usr/local/plexdata/Plex Media Server
[INFO ] - 2021-11-14 13:16:27 @ ImdbDockerImplementation.bootstrap: Capabilities: [NO_TV, DONT_THROW_ON_ENCODING_ERROR]
[INFO ] - 2021-11-14 13:16:27 @ Main.main: << INIT SUCCESS >>
[INFO ] - 2021-11-14 13:16:27 @ Scheduler.go: Scheduler is loading tasks... Blocking until completely set-up and ready to go.
[INFO ] - 2021-11-14 13:16:27 @ Scheduler.go: Scheduling tasks...
[INFO ] - 2021-11-14 13:16:27 @ Scheduler.lambda$go$0: Scheduled imdb-docker task to run @ every 1 hour(s).
[INFO ] - 2021-11-14 13:16:27 @ Scheduler.lambda$go$1: Queued task imdb-docker for immediate execution.
[INFO ] - 2021-11-14 13:16:27 @ Scheduler.go: Running supplied tasks immediately NOW!
[INFO ] - 2021-11-14 13:16:27 @ TaskWrapper.run: ================================================
[INFO ] - 2021-11-14 13:16:27 @ TaskWrapper.run: Starting task: imdb-docker | Execution count: 0
[INFO ] - 2021-11-14 13:16:27 @ TaskWrapper.run: ================================================
[ERROR] - 2021-11-14 13:16:27 @ ImdbDockerImplementation$ImdbBatchJob.run: IllegalArgumentException exception encountered...
[ERROR] - 2021-11-14 13:16:27 @ ImdbDockerImplementation$ImdbBatchJob.run: Please contact the maintainer of the application with the stacktrace below if you think this is unwanted behavior.
[ERROR] - 2021-11-14 13:16:27 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2021-11-14 13:16:27 @ ImdbDockerImplementation$ImdbBatchJob.run: java.lang.IllegalArgumentException: capacity < 0: (-455198112 < 0)
        at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
        at java.base/java.nio.CharBuffer.allocate(CharBuffer.java:347)
        at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:794)
        at java.base/java.nio.charset.Charset.decode(Charset.java:814)
        at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507)
        at org.sqlite.core.NativeDB.column_name(NativeDB.java:239)
        at org.sqlite.core.DB.column_names(DB.java:733)
        at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
        at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
        at updatetool.common.SqliteDatabaseProvider.queryFor(SqliteDatabaseProvider.java:39)
        at updatetool.common.DatabaseSupport.requestLibrary(DatabaseSupport.java:83)
        at updatetool.common.DatabaseSupport.requestMovieLibraries(DatabaseSupport.java:62)
        at updatetool.imdb.ImdbDockerImplementation$ImdbBatchJob.run(ImdbDockerImplementation.java:226)
        at updatetool.TaskWrapper.run(Main.java:252)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
[ERROR] - 2021-11-14 13:16:27 @ ImdbDockerImplementation$ImdbBatchJob.run: ========================================
[ERROR] - 2021-11-14 13:16:27 @ ImdbDockerImplementation$ImdbBatchJob.run: The application will terminate now.

If I restart the application it will eventually run without crashing. Any idea what that above error is from?
Running in truenas jail 11.2-RELEASE  with openjdk version "12.0.2" 2019-07-16

**Comment by tostlund** [comment]
I upgraded my java to openjdk version "16.0.1" 2021-04-20 and all my issues seem to have gone away.
