### ISSUE TITLE
Gui has stopped working for seemingly no reason

### ISSUE THREAD

**Issue by PaddyD95** [mynttt/UpdateTool#90]
The tool has been working fine for over a year since I installed it. I use a .bat file to open the GUI file, nothing about my set up or file system has changed but all of a sudden I'm getting the following error:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

  java.io.EOFException

    at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2860)
    at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3355)
    at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:939)
    at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:381)
    at updatetool.gui.Config.load(Config.java:37)
    at updatetool.gui.Config.<clinit>(Config.java:49)
    at updatetool.gui.App.initialize(App.java:93)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
    at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2591)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3237)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3194)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3163)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3136)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3113)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3106)
    at updatetool.gui.App.start(App.java:65)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Thread.java:831)

I've tried using the newer releases of the tool but that hasn't worked either

**Comment by mynttt** [comment]
Hi! This is a very strange error. Usually it indicates that a dependency required for the logging library is missing or that something fucked up the classpath and created an internal conflict which prevents loading the class correctly.

Which version of the JDK are you using?

How are you starting the GUI exactly?

Does this issue still persist?

Have you installed any kind of Java application or made changes to the environment before this happened if you happen to remember?

**Comment by PaddyD95** [comment]
I was using version 16, am now using version 18.
I'm starting the gui via a .bat file, but I get the same error if I try through the command prompt..
If I click on it directly nothing happens. Brief loading wheel and then nothing.
I haven't installed anything or made any changes that I can think of that would affect java in any way.

**Comment by mynttt** [comment]
@PaddyD95 I've not recieved a notification about this, sorry for the late reply. I will test this out on a different system with your Java version. Maybe something is wrong with the build.

**Comment by mynttt** [comment]
Has this resolved itself? And if not what if you remove all Java installations and only install the latest LTS from https://adoptium.net/?
